/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* READLINE DEF */
/* #undef HAVE_READLINE */

/* Name of package */
#define PACKAGE "clann"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "chris.creevey@gmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "clann"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "clann 3.1.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "clann"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.1.3"

/* Version number of package */
#define VERSION "3.1.3"
