/* Auto-generated from tools/clannview.template.html by tools/gen_viewer_template.py -- do not edit by hand. */
#ifndef VIEWER_TEMPLATE_H
#define VIEWER_TEMPLATE_H

static const char *VIEWER_HTML_HEAD =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>Clann tree viewer</title>\n"
"<style>\n"
"  :root{\n"
"    --bg:#f7f7f8; --panel:#ffffff; --ink:#1c1d20; --muted:#6a6d75; --line:#c9ccd2;\n"
"    --branch:#3a3d44; --accent:#2f6df6; --dup:#d9482b; --spec:#3a3d44; --loss:#9aa0aa;\n"
"    --sel:#2f6df6; --hl:#ffd24d;\n"
"  }\n"
"  :root[data-theme=\"dark\"]{\n"
"    --bg:#16171a; --panel:#1f2126; --ink:#e9eaee; --muted:#9a9ea8; --line:#3a3d44;\n"
"    --branch:#c4c8d0; --accent:#6ea0ff; --dup:#ff6b4a; --spec:#c4c8d0; --loss:#6b7079;\n"
"    --sel:#6ea0ff; --hl:#b9902a;\n"
"  }\n"
"  *{box-sizing:border-box}\n"
"  html,body{height:100%;margin:0}\n"
"  body{font:13px/1.4 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif;\n"
"       color:var(--ink);background:var(--bg);display:flex;flex-direction:column}\n"
"  header{display:flex;align-items:center;gap:14px;padding:8px 12px;border-bottom:1px solid var(--line);background:var(--panel)}\n"
"  header .title{font-weight:600}\n"
"  header .meta{color:var(--muted);font-size:12px}\n"
"  header .meta b{color:var(--ink);font-weight:600}\n"
"  .spacer{flex:1}\n"
"  #nav{display:none;align-items:center;gap:5px}\n"
"  #nav button{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:6px;\n"
"              width:26px;height:24px;cursor:pointer;font-size:11px;line-height:1}\n"
"  #nav button:hover{border-color:var(--accent)}\n"
"  #nav select{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:6px;\n"
"              padding:3px 6px;font:inherit;max-width:220px}\n"
"  #nav input[type=search]{border:1px solid var(--line);background:var(--bg);color:var(--ink);border-radius:6px;\n"
"              padding:3px 7px;font:inherit;width:130px}\n"
"  #nav input[type=search].hit{border-color:var(--accent)}\n"
"  #nav input[type=search].miss{border-color:var(--dup)}\n"
"  main{flex:1;display:flex;min-height:0}\n"
"  #side{width:230px;flex:none;border-right:1px solid var(--line);background:var(--panel);\n"
"        overflow:auto;padding:10px}\n"
"  #side h4{margin:12px 0 6px;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}\n"
"  #side h4:first-child{margin-top:0}\n"
"  .row{display:flex;align-items:center;gap:8px;margin:5px 0}\n"
"  .row label{flex:1;user-select:none}\n"
"  .seg{display:flex;border:1px solid var(--line);border-radius:6px;overflow:hidden}\n"
"  .seg button{flex:1;border:0;background:transparent;color:var(--ink);padding:4px 6px;cursor:pointer;font:inherit}\n"
"  .seg button.on{background:var(--accent);color:#fff}\n"
"  input[type=range]{width:100%}\n"
"  input[type=search]{width:100%;padding:4px 6px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--ink)}\n"
"  button.act{width:100%;padding:5px 8px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--ink);cursor:pointer;margin:3px 0;font:inherit}\n"
"  button.act:hover{border-color:var(--accent)}\n"
"  button.act.warn{color:var(--dup)}\n"
"  #wrap{flex:1;position:relative;overflow:hidden}\n"
"  svg{width:100%;height:100%;display:block;cursor:grab;background:var(--bg)}\n"
"  svg.grab{cursor:grabbing}\n"
"  svg.reroot{cursor:crosshair}\n"
"  .branch{stroke:var(--branch);stroke-width:1.5;fill:none}\n"
"  .branch.hit{stroke:transparent;stroke-width:9;cursor:pointer}\n"
"  .branch.sel{stroke:var(--sel);stroke-width:2.5}\n"
"  .lossbranch{stroke:var(--loss);stroke-width:1.4;stroke-dasharray:3 3;fill:none}\n"
"  .leaflabel{fill:var(--ink);cursor:default}\n"
"  .leaflabel.dim{fill:var(--muted)}\n"
"  .leaflabel.hl{fill:#000}\n"
"  .intlabel{fill:var(--muted);font-size:10px}\n"
"  .support{fill:var(--muted);font-size:10px}\n"
"  .nodeglyph{cursor:pointer}\n"
"  .hlbox{fill:var(--hl);opacity:.35}\n"
"  .collapsed{fill:var(--branch);opacity:.8;cursor:pointer}\n"
"  .tip{position:absolute;pointer-events:none;background:var(--panel);border:1px solid var(--line);\n"
"       border-radius:6px;padding:6px 8px;font-size:12px;box-shadow:0 4px 14px rgba(0,0,0,.18);max-width:280px;display:none;z-index:5}\n"
"  .tip b{color:var(--ink)} .tip .ev{font-weight:600}\n"
"  .legend{position:absolute;left:10px;bottom:10px;background:var(--panel);border:1px solid var(--line);\n"
"          border-radius:8px;padding:8px 10px;font-size:12px;box-shadow:0 3px 10px rgba(0,0,0,.12)}\n"
"  .legend div{display:flex;align-items:center;gap:7px;margin:3px 0}\n"
"  .sw{width:14px;height:14px;flex:none;display:inline-block}\n"
"  .hint{color:var(--muted);font-size:11px;margin-top:6px}\n"
"  kbd{border:1px solid var(--line);border-bottom-width:2px;border-radius:4px;padding:0 4px;font-size:11px;background:var(--bg)}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <span class=\"title\" id=\"hTitle\">Clann tree viewer</span>\n"
"  <span id=\"nav\">\n"
"    <input type=\"search\" id=\"treeSearch\" placeholder=\"filter trees…\" title=\"Filter trees by name, number, or a taxon they contain\">\n"
"    <button id=\"prevT\" title=\"Previous match (←)\">◀</button>\n"
"    <select id=\"selT\" title=\"Jump to tree\"></select>\n"
"    <button id=\"nextT\" title=\"Next match (→)\">▶</button>\n"
"    <span class=\"meta\" id=\"cntT\"></span>\n"
"  </span>\n"
"  <span class=\"meta\" id=\"hMeta\"></span>\n"
"  <span class=\"spacer\"></span>\n"
"  <button class=\"act\" style=\"width:auto\" id=\"themeBtn\" title=\"Toggle light/dark\">◐</button>\n"
"</header>\n"
"<main>\n"
"  <aside id=\"side\">\n"
"    <h4>Layout</h4>\n"
"    <div class=\"row\"><div class=\"seg\" id=\"segLayout\" style=\"flex:1\">\n"
"      <button data-v=\"clado\" class=\"on\">Cladogram</button><button data-v=\"phylo\">Phylogram</button>\n"
"    </div></div>\n"
"    <div class=\"row\"><label>Row spacing</label></div>\n"
"    <input type=\"range\" id=\"vspace\" min=\"10\" max=\"46\" value=\"20\">\n"
"    <div class=\"row\"><label>Font size</label></div>\n"
"    <input type=\"range\" id=\"fsize\" min=\"8\" max=\"20\" value=\"12\">\n"
"\n"
"    <h4>Show</h4>\n"
"    <div class=\"row\"><label for=\"tSupport\">Support values</label><input type=\"checkbox\" id=\"tSupport\" checked></div>\n"
"    <div class=\"row\"><label for=\"tLen\">Branch lengths</label><input type=\"checkbox\" id=\"tLen\"></div>\n"
"    <div class=\"row\"><label for=\"tInt\">Internal labels</label><input type=\"checkbox\" id=\"tInt\"></div>\n"
"    <div class=\"row\"><label for=\"tAlign\">Align tip labels</label><input type=\"checkbox\" id=\"tAlign\"></div>\n"
"    <div class=\"row\" id=\"rowLoss\"><label for=\"tLoss\">Losses</label><input type=\"checkbox\" id=\"tLoss\" checked></div>\n"
"    <div class=\"row\" id=\"rowScale\"><label for=\"tScale\">Scale bar</label><input type=\"checkbox\" id=\"tScale\" checked></div>\n"
"\n"
"    <h4>Find</h4>\n"
"    <input type=\"search\" id=\"find\" placeholder=\"highlight taxa (comma-sep)…\">\n"
"\n"
"    <h4>Edit</h4>\n"
"    <div class=\"row\"><label>Reroot mode</label><input type=\"checkbox\" id=\"rerootMode\"></div>\n"
"    <div class=\"hint\">Click a branch to reroot there. Click a node dot to collapse/expand.</div>\n"
"    <button class=\"act\" id=\"ladder\">Ladderize ⇅</button>\n"
"    <button class=\"act\" id=\"expandAll\">Expand all</button>\n"
"    <button class=\"act warn\" id=\"reset\">Reset view</button>\n"
"\n"
"    <h4>Export</h4>\n"
"    <button class=\"act\" id=\"expSvg\">Download SVG</button>\n"
"    <button class=\"act\" id=\"expNwk\">Copy Newick (current rooting)</button>\n"
"    <div class=\"hint\" style=\"margin-top:10px\">Scroll to zoom · drag to pan · <kbd>R</kbd> reroot toggle</div>\n"
"  </aside>\n"
"  <div id=\"wrap\">\n"
"    <svg id=\"svg\"><g id=\"scene\"></g></svg>\n"
"    <div class=\"tip\" id=\"tip\"></div>\n"
"    <div class=\"legend\" id=\"legend\"></div>\n"
"  </div>\n"
"</main>\n"
"\n"
"<script>\n"
"/* ============================ EMBEDDED DATA ============================\n"
"   Clann replaces the DATA object below. Format:\n"
"   { type:\"tree\"|\"reconciliation\", meta:{...},\n"
"     tree:{ name, length, support, event, species, children:[...] } }\n"
"   event ∈ {null|\"speciation\"|\"duplication\"|\"loss\"}; species = mapped species name. */\n"
"const DATA = /*CLANN_DATA_BEGIN*/";

static const char *VIEWER_HTML_TAIL =
"/*CLANN_DATA_END*/;\n"
"/* ====================================================================== */\n"
"\n"
"// ---------- model ----------\n"
"let ID=0;\n"
"function build(n, parent){\n"
"  n.id=ID++; n.parent=parent||null; n.collapsed=false;\n"
"  n.children=(n.children||[]).map(c=>build(c,n));\n"
"  n.isLeaf = n.children.length===0 && n.event!==\"loss\";\n"
"  n.isLoss = n.event===\"loss\";\n"
"  return n;\n"
"}\n"
"function leaves(n,acc){acc=acc||[];if(n.collapsed||(!n.children.length)){if(!n.isLoss||showLoss)acc.push(n);}else n.children.forEach(c=>leaves(c,acc));return acc;}\n"
"function each(n,f){f(n);n.children.forEach(c=>each(c,f));}\n"
"function depthOf(n){let d=0,p=n;while(p.parent){d++;p=p.parent;}return d;}\n"
"function maxDepth(root){let m=0;each(root,n=>{if(!n.collapsed){m=Math.max(m,depthOf(n));}});return m;}\n"
"\n"
"// ---------- state ----------\n"
"const isRecon = DATA.type===\"reconciliation\";\n"
"// normalise to a list of trees (single-tree files still work)\n"
"const TREES = Array.isArray(DATA.trees) ? DATA.trees\n"
"            : [{name:(DATA.meta&&DATA.meta.title)||(isRecon?\"reconciliation\":\"tree\"), tree:DATA.tree,\n"
"                score:DATA.meta&&DATA.meta.score, dups:DATA.meta&&DATA.meta.dups, losses:DATA.meta&&DATA.meta.losses}];\n"
"let curIdx=0;\n"
"function curEntry(){ return TREES[curIdx]||{}; }\n"
"let root=build(structuredClone(curEntry().tree),null);\n"
"let showLoss=true, layout=\"clado\", vspace=20, fsize=12;\n"
"let opt={support:true,len:false,intl:false,align:false,scale:true};\n"
"let view={k:1,x:40,y:20};\n"
"let rerootOn=false, hlSet=new Set();\n"
"\n"
"// ---------- layout ----------\n"
"function computeLayout(){\n"
"  // y by leaf order\n"
"  const ls=[]; (function order(n){ if(n.collapsed||!n.children.length){ if(!n.isLoss||showLoss) ls.push(n);} else n.children.forEach(order);} )(root);\n"
"  ls.forEach((n,i)=>n._y=i*vspace);\n"
"  // internal y = mean of visible children\n"
"  (function setY(n){\n"
"    if(n.collapsed||!n.children.length) return n._y;\n"
"    const ys=n.children.filter(c=>!c.isLoss||showLoss).map(setY);\n"
"    n._y = ys.length? (Math.min(...ys)+Math.max(...ys))/2 : (n._y||0);\n"
"    return n._y;\n"
"  })(root);\n"
"  // x\n"
"  const md=Math.max(1,maxDepth(root));\n"
"  let maxLen=0; (function cl(n,acc){n._cl=acc;maxLen=Math.max(maxLen,acc);if(!n.collapsed)n.children.forEach(c=>cl(c,acc+(c.length||0)));})(root,0);\n"
"  const W=Math.max(360, (typeof innerWidth!=='undefined'?innerWidth:900)-560);\n"
"  const xstep=Math.max(26, W/(md+1));\n"
"  each(root,n=>{\n"
"    if(layout===\"phylo\" && maxLen>0){ n._x = (n._cl/maxLen)*(W-10); }\n"
"    else { n._x = depthOf(n)*xstep; }\n"
"  });\n"
"  root._x = layout===\"phylo\"?0:0;\n"
"  return {ls, W, maxLen};\n"
"}\n"
"\n"
"// ---------- render ----------\n"
"const svg=document.getElementById('svg'), scene=document.getElementById('scene'), tip=document.getElementById('tip');\n"
"function el(t,a){const e=document.createElementNS('http://www.w3.org/2000/svg',t);for(const k in a)e.setAttribute(k,a[k]);return e;}\n"
"function render(){\n"
"  const {ls}=computeLayout();\n"
"  scene.innerHTML='';\n"
"  const tipX = Math.max(...leaves(root).map(n=>n._x));\n"
"  // edges\n"
"  each(root,n=>{\n"
"    if(!n.parent) return;\n"
"    if(n.isLoss && !showLoss) return;\n"
"    const p=n.parent;\n"
"    const cls = n.isLoss?'lossbranch':'branch';\n"
"    // elbow: vertical at parent.x, horizontal to n.x\n"
"    const path=`M${p._x},${p._y} V${n._y} H${n._x}`;\n"
"    scene.appendChild(el('path',{d:path,class:cls}));\n"
"    if(!n.isLoss){\n"
"      const hit=el('path',{d:path,class:'branch hit','data-id':n.id});\n"
"      hit.addEventListener('click',ev=>{ev.stopPropagation(); if(rerootOn) doReroot(n); else selectBranch(n);});\n"
"      hit.addEventListener('mousemove',e=>showTip(e,n,true));\n"
"      hit.addEventListener('mouseleave',hideTip);\n"
"      scene.appendChild(hit);\n"
"    }\n"
"  });\n"
"  // vertical connectors handled by V in path above; but ensure the parent's vertical spans children:\n"
"  each(root,n=>{\n"
"    if(n.collapsed||n.children.length<2) return;\n"
"    const vis=n.children.filter(c=>!c.isLoss||showLoss);\n"
"    if(vis.length<2) return;\n"
"    const y0=Math.min(...vis.map(c=>c._y)), y1=Math.max(...vis.map(c=>c._y));\n"
"    scene.appendChild(el('path',{d:`M${n._x},${y0} V${y1}`,class:'branch'}));\n"
"  });\n"
"  // nodes + labels\n"
"  each(root,n=>{\n"
"    if(n.isLoss){ if(showLoss){ // loss stub marker\n"
"        scene.appendChild(el('circle',{cx:n._x,cy:n._y,r:3.2,fill:'none',stroke:'var(--loss)','stroke-width':1.4}));\n"
"        const t=el('text',{x:n._x+7,y:n._y+3.5,class:'intlabel','font-size':Math.max(9,fsize-2)});\n"
"        t.textContent='✕ '+(n.species||'loss'); t.style.fill='var(--loss)'; scene.appendChild(t);\n"
"      } return; }\n"
"    if(n.collapsed){\n"
"      // triangle\n"
"      const nleaf=leaves(n).length||1, h=Math.min(60,6+nleaf*3);\n"
"      const tri=el('path',{d:`M${n._x},${n._y} L${n._x+34},${n._y-h/2} L${n._x+34},${n._y+h/2} Z`,class:'collapsed'});\n"
"      tri.addEventListener('click',ev=>{ev.stopPropagation();n.collapsed=false;render();});\n"
"      scene.appendChild(tri);\n"
"      const t=el('text',{x:n._x+40,y:n._y+4,class:'leaflabel','font-size':fsize});\n"
"      t.textContent=(n.name||('▸ '+nleaf+' taxa')); scene.appendChild(t);\n"
"      return;\n"
"    }\n"
"    if(n.isLeaf){\n"
"      const lx = opt.align? tipX+8 : n._x+7;\n"
"      if(opt.align && lx>n._x+7) scene.appendChild(el('path',{d:`M${n._x},${n._y} H${lx-3}`,class:'lossbranch'}));\n"
"      const t=el('text',{x:lx,y:n._y+fsize*0.34,class:'leaflabel','font-size':fsize});\n"
"      t.textContent=n.name||'?';\n"
"      if(hlSet.size){ if(matchHL(n)) t.classList.add('hl'); else t.classList.add('dim'); }\n"
"      t.addEventListener('mousemove',e=>showTip(e,n,false));\n"
"      t.addEventListener('mouseleave',hideTip);\n"
"      scene.appendChild(t);\n"
"    }\n"
"    // node glyph (event)\n"
"    if(isRecon && n.children.length){\n"
"      let g;\n"
"      if(n.event===\"duplication\"){ g=el('rect',{x:n._x-4,y:n._y-4,width:8,height:8,fill:'var(--dup)',class:'nodeglyph'}); }\n"
"      else { g=el('circle',{cx:n._x,cy:n._y,r:3,fill:'var(--spec)',class:'nodeglyph'}); }\n"
"      g.setAttribute('data-id',n.id);\n"
"      g.addEventListener('click',ev=>{ev.stopPropagation(); n.collapsed=!n.collapsed; render();});\n"
"      g.addEventListener('mousemove',e=>showTip(e,n,false));\n"
"      g.addEventListener('mouseleave',hideTip);\n"
"      scene.appendChild(g);\n"
"    } else if(!isRecon && n.children.length){\n"
"      const g=el('circle',{cx:n._x,cy:n._y,r:2.6,fill:'var(--branch)',class:'nodeglyph'});\n"
"      g.addEventListener('click',ev=>{ev.stopPropagation();n.collapsed=!n.collapsed;render();});\n"
"      scene.appendChild(g);\n"
"    }\n"
"    // support / internal labels\n"
"    if(n.children.length && !n.collapsed){\n"
"      if(opt.support && n.support!=null){\n"
"        const t=el('text',{x:n._x-4,y:n._y-5,class:'support','text-anchor':'end'}); t.textContent=n.support; scene.appendChild(t);\n"
"      }\n"
"      if(opt.intl && n.name){\n"
"        const t=el('text',{x:n._x+5,y:n._y-5,class:'intlabel'}); t.textContent=n.name; scene.appendChild(t);\n"
"      }\n"
"    }\n"
"  });\n"
"  // branch length labels\n"
"  if(opt.len && layout===\"phylo\"){\n"
"    each(root,n=>{ if(n.parent && n.length && !n.isLoss){ const t=el('text',{x:(n.parent._x+n._x)/2,y:n._y-3,class:'support','text-anchor':'middle'}); t.textContent=(+n.length).toFixed(3); scene.appendChild(t);} });\n"
"  }\n"
"  applyView();\n"
"  drawLegend();\n"
"}\n"
"function selectBranch(n){ document.querySelectorAll('.branch.sel').forEach(e=>e.classList.remove('sel')); }\n"
"function matchHL(n){ const s=(n.name||'')+' '+(n.species||''); return [...hlSet].some(q=>s.toLowerCase().includes(q)); }\n"
"\n"
"// ---------- reroot ----------\n"
"function doReroot(node){\n"
"  // reroot on the edge above `node`: new root between node and node.parent\n"
"  if(!node.parent) return;\n"
"  // collect path node -> ... -> oldroot\n"
"  const nr={name:\"\",children:[],event:isRecon?\"speciation\":null};\n"
"  let cur=node, par=node.parent;\n"
"  // detach node from par\n"
"  removeChild(par,cur);\n"
"  nr.children.push(cur); cur.parent=nr;\n"
"  // reverse the chain up to root\n"
"  let prev=nr, child=par;\n"
"  while(child){\n"
"    const up=child.parent;\n"
"    if(up) removeChild(up,child);\n"
"    child.parent=prev; prev.children.push(child);\n"
"    prev=child; child=up;\n"
"  }\n"
"  // recompute events for recon (mapping is now stale -> mark unknown)\n"
"  ID=0; root=build(nr,null);\n"
"  if(isRecon){ each(root,n=>{ if(n.children.length && !n.isLoss){ n.event=n.event||\"speciation\"; }}); staleWarn=true; updateMeta(); }\n"
"  render();\n"
"}\n"
"function removeChild(p,c){ p.children=p.children.filter(x=>x!==c); }\n"
"let staleWarn=false;\n"
"\n"
"// ---------- newick ----------\n"
"function toNewick(n){\n"
"  if(!n.children.length){ return (n.name||'').replace(/[(),:;]/g,'_') + (n.length!=null?':'+n.length:''); }\n"
"  return '('+n.children.filter(c=>!c.isLoss).map(toNewick).join(',')+')'+(n.support!=null?n.support:'')+(n.length!=null?':'+n.length:'');\n"
"}\n"
"\n"
"// ---------- view / zoom / pan ----------\n"
"function applyView(){ scene.setAttribute('transform',`translate(${view.x},${view.y}) scale(${view.k})`); }\n"
"svg.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect();const mx=e.clientX-r.left,my=e.clientY-r.top;\n"
"  const f=Math.exp(-e.deltaY*0.0015); const nk=Math.min(8,Math.max(0.15,view.k*f));\n"
"  view.x=mx-(mx-view.x)*(nk/view.k); view.y=my-(my-view.y)*(nk/view.k); view.k=nk; applyView();},{passive:false});\n"
"let drag=null;\n"
"svg.addEventListener('mousedown',e=>{ if(e.target.classList.contains('branch')&&e.target.classList.contains('hit'))return; drag={x:e.clientX-view.x,y:e.clientY-view.y}; svg.classList.add('grab');});\n"
"window.addEventListener('mousemove',e=>{ if(drag){view.x=e.clientX-drag.x;view.y=e.clientY-drag.y;applyView();}});\n"
"window.addEventListener('mouseup',()=>{drag=null;svg.classList.remove('grab');});\n"
"\n"
"// ---------- tooltip ----------\n"
"function showTip(e,n,isBranch){\n"
"  const r=document.getElementById('wrap').getBoundingClientRect();\n"
"  let h='';\n"
"  if(n.isLeaf||!n.children.length){ h=`<b>${n.name||'?'}</b>`; if(n.species)h+=`<br>species: <b>${n.species}</b>`; }\n"
"  else { h=`<span class=\"ev\" style=\"color:${n.event==='duplication'?'var(--dup)':'var(--spec)'}\">${(n.event||'node').toUpperCase()}</span>`;\n"
"         h+=`<br>${countLeaves(n)} descendant tips`; if(n.support!=null)h+=`<br>support: ${n.support}`; }\n"
"  if(isBranch && n.length!=null) h+=`<br>length: ${(+n.length).toFixed(4)}`;\n"
"  if(isBranch) h+=`<br><span style=\"color:var(--muted)\">${rerootOn?'click: reroot here':'click a node dot to collapse'}</span>`;\n"
"  tip.innerHTML=h; tip.style.display='block';\n"
"  tip.style.left=Math.min(r.width-tip.offsetWidth-6, e.clientX-r.left+12)+'px';\n"
"  tip.style.top=(e.clientY-r.top+12)+'px';\n"
"}\n"
"function hideTip(){tip.style.display='none';}\n"
"function countLeaves(n){let c=0;each(n,x=>{if(!x.children.length&&!x.isLoss)c++;});return c;}\n"
"\n"
"// ---------- legend ----------\n"
"function drawLegend(){\n"
"  const L=document.getElementById('legend');\n"
"  if(!isRecon){L.style.display='none';return;}\n"
"  L.style.display='block';\n"
"  L.innerHTML=`<div><span class=\"sw\" style=\"background:var(--dup)\"></span>Duplication</div>`+\n"
"    `<div><span class=\"sw\" style=\"background:var(--spec);border-radius:50%\"></span>Speciation</div>`+\n"
"    (showLoss?`<div><span class=\"sw\" style=\"border:1.4px dashed var(--loss)\"></span>Loss</div>`:'');\n"
"}\n"
"\n"
"// ---------- controls ----------\n"
"function updateMeta(){\n"
"  const m=DATA.meta||{}, e=curEntry();\n"
"  document.getElementById('hTitle').textContent=e.name||m.title||(isRecon?'Reconciliation':'Tree');\n"
"  let s=[];\n"
"  if(m.dataset)s.push(m.dataset);\n"
"  if(m.criterion)s.push('criterion: <b>'+m.criterion+'</b>');\n"
"  if(m.lossmodel)s.push('lossmodel: <b>'+m.lossmodel+'</b>');\n"
"  if(e.score!=null)s.push('score: <b>'+e.score+'</b>');\n"
"  if(e.dups!=null)s.push('<b>'+e.dups+'</b> dup');\n"
"  if(e.losses!=null)s.push('<b>'+e.losses+'</b> loss');\n"
"  if(staleWarn)s.push('<span style=\"color:var(--dup)\">⚠ re-rooted: mapping stale</span>');\n"
"  document.getElementById('hMeta').innerHTML=s.join(' · ');\n"
"}\n"
"let filtered = TREES.map((_,i)=>i);   // tree indices currently matching the filter\n"
"function treeLabel(i){ const t=TREES[i]; return (t.name||('tree '+(i+1)))+(t.score!=null?'  ('+t.score+')':''); }\n"
"function navCounter(){\n"
"  const c=document.getElementById('cntT'), pos=filtered.indexOf(curIdx);\n"
"  if(filtered.length===TREES.length) c.textContent=(curIdx+1)+' / '+TREES.length;\n"
"  else c.textContent=(pos>=0?(pos+1):'–')+' / '+filtered.length+' matched (of '+TREES.length+')';\n"
"}\n"
"function rebuildDropdown(){\n"
"  const sel=document.getElementById('selT'); sel.innerHTML='';\n"
"  filtered.forEach(i=>{ const o=document.createElement('option'); o.value=i; o.textContent=treeLabel(i); sel.appendChild(o); });\n"
"  if(filtered.indexOf(curIdx)>=0) sel.value=curIdx;\n"
"}\n"
"function loadTree(i){\n"
"  curIdx=i;\n"
"  ID=0; root=build(structuredClone(curEntry().tree),null);\n"
"  staleWarn=false; hlSet=new Set(); document.getElementById('find').value='';\n"
"  view={k:1,x:40,y:20};\n"
"  const sel=document.getElementById('selT'); if([...sel.options].some(o=>+o.value===i)) sel.value=i;\n"
"  navCounter(); updateMeta(); render();\n"
"}\n"
"function stepTree(d){\n"
"  if(!filtered.length) return;\n"
"  let pos=filtered.indexOf(curIdx); if(pos<0) pos = d>0?-1:0;\n"
"  loadTree(filtered[(pos+d+filtered.length)%filtered.length]);\n"
"}\n"
"function applyTreeFilter(q){\n"
"  const box=document.getElementById('treeSearch');\n"
"  q=(q||'').trim().toLowerCase();\n"
"  filtered = !q ? TREES.map((_,i)=>i)\n"
"                : TREES.map((_,i)=>i).filter(i=> TREES[i]._search.includes(q) || String(i+1)===q );\n"
"  box.classList.toggle('hit', !!q && filtered.length>0);\n"
"  box.classList.toggle('miss', !!q && filtered.length===0);\n"
"  rebuildDropdown(); navCounter();\n"
"  if(filtered.length && filtered.indexOf(curIdx)<0) loadTree(filtered[0]);   // jump to first match\n"
"}\n"
"function setupNav(){\n"
"  const nav=document.getElementById('nav');\n"
"  // precompute per-tree search text: name + contained taxa (leaf names & species)\n"
"  TREES.forEach((e,i)=>{\n"
"    const taxa=new Set();\n"
"    (function walk(n){ if(!n) return;\n"
"      if(!n.children||!n.children.length){ if(n.name)taxa.add(String(n.name).toLowerCase()); if(n.species)taxa.add(String(n.species).toLowerCase()); }\n"
"      else (n.children||[]).forEach(walk); })(e.tree);\n"
"    e._search = String(e.name||('tree_'+i)).toLowerCase()+' '+[...taxa].join(' ');\n"
"  });\n"
"  if(TREES.length<2){ nav.style.display='none'; return; }\n"
"  nav.style.display='inline-flex';\n"
"  rebuildDropdown();\n"
"  document.getElementById('selT').onchange=e=>loadTree(+e.target.value);\n"
"  document.getElementById('prevT').onclick=()=>stepTree(-1);\n"
"  document.getElementById('nextT').onclick=()=>stepTree(1);\n"
"  document.getElementById('treeSearch').oninput=e=>applyTreeFilter(e.target.value);\n"
"  navCounter();\n"
"}\n"
"document.getElementById('segLayout').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;\n"
"  [...e.currentTarget.children].forEach(x=>x.classList.remove('on'));b.classList.add('on');layout=b.dataset.v;\n"
"  document.getElementById('rowScale').style.display=layout==='phylo'?'flex':'none';render();});\n"
"document.getElementById('vspace').oninput=e=>{vspace=+e.target.value;render();};\n"
"document.getElementById('fsize').oninput=e=>{fsize=+e.target.value;render();};\n"
"const chk=(id,k)=>{document.getElementById(id).onchange=e=>{opt[k]=e.target.checked;render();};};\n"
"chk('tSupport','support');chk('tLen','len');chk('tInt','intl');chk('tAlign','align');chk('tScale','scale');\n"
"document.getElementById('tLoss').onchange=e=>{showLoss=e.target.checked;render();};\n"
"document.getElementById('find').oninput=e=>{hlSet=new Set(e.target.value.split(',').map(s=>s.trim().toLowerCase()).filter(Boolean));render();};\n"
"document.getElementById('rerootMode').onchange=e=>{rerootOn=e.target.checked;svg.classList.toggle('reroot',rerootOn);};\n"
"document.getElementById('ladder').onclick=()=>{ (function lad(n){n.children.sort((a,b)=>countLeaves(a)-countLeaves(b));n.children.forEach(lad);})(root); render();};\n"
"document.getElementById('expandAll').onclick=()=>{each(root,n=>n.collapsed=false);render();};\n"
"document.getElementById('reset').onclick=()=>loadTree(curIdx);\n"
"document.getElementById('themeBtn').onclick=()=>{const r=document.documentElement;r.dataset.theme=r.dataset.theme==='dark'?'light':'dark';};\n"
"document.getElementById('expSvg').onclick=()=>{const s=new XMLSerializer().serializeToString(svg);const b=new Blob([s],{type:'image/svg+xml'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(DATA.meta&&DATA.meta.title||'tree')+'.svg';a.click();};\n"
"document.getElementById('expNwk').onclick=()=>{const nwk=toNewick(root)+';';navigator.clipboard&&navigator.clipboard.writeText(nwk);document.getElementById('expNwk').textContent='Copied ✓';setTimeout(()=>document.getElementById('expNwk').textContent='Copy Newick (current rooting)',1200);};\n"
"window.addEventListener('keydown',e=>{\n"
"  if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;\n"
"  if(e.key==='r'||e.key==='R'){const c=document.getElementById('rerootMode');c.checked=!c.checked;c.onchange({target:c});}\n"
"  else if(e.key==='ArrowLeft'&&TREES.length>1)stepTree(-1);\n"
"  else if(e.key==='ArrowRight'&&TREES.length>1)stepTree(1);\n"
"});\n"
"window.addEventListener('resize',render);\n"
"\n"
"// init\n"
"if(!isRecon){document.getElementById('rowLoss').style.display='none';document.getElementById('legend').style.display='none';}\n"
"document.getElementById('rowScale').style.display=layout==='phylo'?'flex':'none';\n"
"setupNav(); updateMeta(); render();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif
